name: "Quality"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["c"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{matrix.language}}
    - name: Setup (Dependencies)
      run: source setup.sh
    - name: Setup terminal variable
      run: export TERM=dumb
    - name: Build
      run: source build.sh
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
